server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    statusPageUrlPath: $ {server.servletPath} / info
    healthCheckUrlPath: $ {server.servletPath} / health